language: node_js
os: linux
node_js:
  - '14'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install codecov -g
  - npm ci --ignore-scripts
script:
  #run build script specified in package.json
  - npm i webdriver-manager
  - npm run ci
  # call script for deploying of produced artifacts
  - bash ./.travis-deploy.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/portfolio
  on:
    branch: release
after_success:
  - codecov
